# Generated by Django 5.1.1 on 2024-09-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
