### Register User
POST http://localhost:8000/api/v1/users/register
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com",
    "password": "securepassword",
    "first_name": "First",
    "last_name": "Last"
}

### Login User
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "securepassword"
}

### Get User Profile
GET http://localhost:8000/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2MzMzNTIyLCJpYXQiOjE3MjYzMzI2MjIsImp0aSI6ImMzOWUzYTI4ZDg2YjQ2OTFiYjNiOWY1MzllZTJjODQ3IiwidXNlcl9pZCI6MX0.j2zMG9B7lWnVkv2aW1Zd_ORCv9F3MJWe_3wfPMRxVAI

### Get All Users
GET http://localhost:8000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2MzMzODUwLCJpYXQiOjE3MjYzMzI5NTAsImp0aSI6IjAwMWM0ZjFiMTZlMzQxNWI5Yzc0ZmY1MWRiY2ExZTcxIiwidXNlcl9pZCI6Mn0.fRaWtHLnI-G_yE1uJt3fv3hemdLpbw0fwbwHasj53fI

### Update User Profile
PUT http://localhost:8000/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2MzMzNTIyLCJpYXQiOjE3MjYzMzI2MjIsImp0aSI6ImMzOWUzYTI4ZDg2YjQ2OTFiYjNiOWY1MzllZTJjODQ3IiwidXNlcl9pZCI6MX0.j2zMG9B7lWnVkv2aW1Zd_ORCv9F3MJWe_3wfPMRxVAI
Content-Type: application/json

{
    "username": "updateduser",
    "email": "updateduser@example.com",
    "first_name": "UpdatedFirst",
    "last_name": "UpdatedLast",
    "address": "123 Updated St.",
    "phone_number": "123-456-7890"
}

### Delete User
DELETE http://localhost:8000/api/v1/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI2MzMzODUwLCJpYXQiOjE3MjYzMzI5NTAsImp0aSI6IjAwMWM0ZjFiMTZlMzQxNWI5Yzc0ZmY1MWRiY2ExZTcxIiwidXNlcl9pZCI6Mn0.fRaWtHLnI-G_yE1uJt3fv3hemdLpbw0fwbwHasj53fI
